name: Push

on:
  push:
    branches:
      - "**"
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: ./
        id: if-test
        with:
          if: ${{ github.event_name == 'push' }}
          ifThen_outA: A
          ifThen_outB: B
          ifThen_outC: C
          elseIf: ${{ github.event_name == 'pull_request' }}
          elseIfThen_outA: D
          elseIfThen_outB: E
          elseIfThen_outC: F
          else_outA: G
          else_outB: H
          else_outC: I
      - run: node ./.github/scripts/assert.js "B" ${{ steps.if-test.outputs.outB }}
      - uses: ./
        id: single-elseIf-test
        with:
          if: ${{ github.event_name == 'pull_request' }}
          ifThen_outA: A
          ifThen_outB: B
          ifThen_outC: C
          elseIf: ${{ github.event_name == 'push' }}
          elseIfThen_outA: D
          elseIfThen_outB: E
          elseIfThen_outC: F
          else_outA: G
          else_outB: H
          else_outC: I
      - run: node ./.github/scripts/assert.js "F" ${{ steps.single-elseIf-test.outputs.outC }}
      - uses: ./
        id: multi-elseIf-test
        with:
          if: ${{ github.event_name == 'pull_request' }}
          ifThen_outA: A
          ifThen_outB: B
          ifThen_outC: C
          elseIf1: ${{ github.event_name == 'label' }}
          elseIfThen1_outA: D
          elseIfThen1_outB: E
          elseIfThen1_outC: F
          elseIf2: ${{ github.event_name == 'push' }}
          elseIfThen2_outA: G
          elseIfThen2_outB: H
          elseIfThen2_outC: I
          elseIf3: ${{ github.event_name == 'issue' }}
          elseIfThen3_outA: J
          elseIfThen3_outB: K
          elseIfThen3_outC: L
          else_outA: M
          else_outB: O
          else_outC: P
      - run: node ./.github/scripts/assert.js "G" ${{ steps.multi-elseIf-test.outputs.outA }}
      - uses: ./
        id: else-test
        with:
          if: ${{ github.event_name == 'pull_request' }}
          ifThen_outA: A
          ifThen_outB: B
          ifThen_outC: C
          elseIf1: ${{ github.event_name == 'label' }}
          elseIfThen1_outA: D
          elseIfThen1_outB: E
          elseIfThen1_outC: F
          elseIf2: ${{ github.event_name == 'issue' }}
          elseIfThen2_outA: G
          elseIfThen2_outB: H
          elseIfThen2_outC: I
          elseIf3: ${{ github.event_name == 'push' }}
          elseIfThen3_outA: J
          elseIfThen3_outB: K
          elseIfThen3_outC: L
          else_outA: M
          else_outB: O
          else_outC: P
      - run: node ./.github/scripts/assert.js "L" ${{ steps.else-test.outputs.outC }}
